# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Chii' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chii
  pod 'JTAppleCalendar', '~>7.0'
  pod 'MKRingProgressView'
  pod 'XLPagerTabStrip', '~>9.0'
  pod 'SwiftChart'
  pod 'SwiftyGif'
end
